"use strict";
const test=require("node:test"), assert=require("node:assert/strict"), vm=require("node:vm"), fs=require("node:fs"), path=require("node:path");
function section(source,start,end){return source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));}
test("dashboard offers initial generation, while approved plans regenerate only in Settings",()=>{
    const source=fs.readFileSync(path.join(__dirname,"../public/js/welcome.js"),"utf8");const actions={hidden:false};const button={hidden:false,classList:{toggle(){}},closest:()=>actions};const context=vm.createContext({generateButton:button,currentPlanId:null});vm.runInContext(section(source,"function setGenerateButtonState(","// Generate a plan"),context);context.setGenerateButtonState("none",false);assert.equal(button.hidden,false);context.setGenerateButtonState("approved",false);assert.equal(button.hidden,true);assert.equal(actions.hidden,true);context.setGenerateButtonState("approved",true);assert.equal(button.hidden,true);context.currentPlanId=7;context.setGenerateButtonState("none",false);assert.equal(button.hidden,true);assert.equal(actions.hidden,true);
});
test("Settings regeneration saves profile before generating and stops if validation fails",async()=>{
    const source=fs.readFileSync(path.join(__dirname,"../public/js/welcome.js"),"utf8");let handler,valid=false;const calls=[];const context=vm.createContext({regenerateBtn:{addEventListener:(event,fn)=>{handler=fn;}},saveSettingsFromForm:async()=>{calls.push("save");return valid;},closeSettings:()=>calls.push("close"),generatePlan:async()=>calls.push("generate")});vm.runInContext(section(source,"if (regenerateBtn) {\n    regenerateBtn.addEventListener", "if (generateButton) {\n    generateButton.addEventListener"),context);await handler();assert.deepEqual(calls,["save"]);calls.length=0;valid=true;await handler();assert.deepEqual(calls,["save","close","generate"]);
});

test("Settings remains available when an existing saved plan cannot be rendered",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/js/welcome.js"),"utf8"); const button={}; const context=vm.createContext({regenerateBtn:button,currentPlanStatus:"none",currentPlanId:7}); vm.runInContext(section(source,"function updateRegenerateButton()", "function getProfileFromStorage()"),context);context.updateRegenerateButton();assert.equal(button.hidden,false);assert.equal(button.disabled,false); });
